### ISSUE TITLE
meta: unfork on GitHub from tendermint/tendermint (complete the hard fork)

### ISSUE THREAD

**Issue by coolaj86** [dashpay/tenderdash#701]
# The Problem

This is being listed as a contributing soft fork (i.e. one that exists for the purpose of doing PRs upstream).

<img width="222" alt="Screenshot 2023-10-23 at 10 58 29 AM" src="https://github.com/dashpay/tenderdash/assets/122831/dab26d7c-d32f-4180-a76a-e21202d95aff">

As such, GitHub is sending bot tags that tell search engines to prefer Tendermint.

# The Solution

Click on the [GitHub Support: Detach Fork](https://support.github.com/contact?flow=detach_fork&subject=Detach%20Fork&tags=rr-forks) at:
- <https://support.github.com/contact?flow=detach_fork&subject=Detach%20Fork&tags=rr-forks>

# Documentation

<img width="564" alt="Screenshot 2023-10-23 at 11 02 09 AM" src="https://github.com/dashpay/tenderdash/assets/122831/17102d93-028a-4d26-b58f-7f198112409f">

**Comment by shumkov** [comment]
Thank you for report. I made a request. Should be done soon

**Comment by shumkov** [comment]
Ok, the repo is detached.
